# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [5]:
import numpy as np

#### Create an array of 10 zeros 

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [14]:
#np.fives(5)
5*np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [16]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [17]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [20]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [23]:
np.random.rand()

0.41106408493117974

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [24]:
np.random.rand(25)

array([0.64898931, 0.27159911, 0.85160062, 0.64492974, 0.46647046,
       0.92459229, 0.30087753, 0.34599116, 0.74626322, 0.25650092,
       0.16824084, 0.06623284, 0.64923633, 0.46323193, 0.87517871,
       0.91518453, 0.62414701, 0.50416943, 0.40550002, 0.08938066,
       0.5984316 , 0.11331236, 0.74143993, 0.40759805, 0.59789098])

#### Create the following matrix:

In [27]:
np.random.random_sample((10,10))

array([[0.44811699, 0.60166514, 0.54974291, 0.12725277, 0.37607783,
        0.03313787, 0.57034828, 0.6440833 , 0.09016248, 0.89302   ],
       [0.8273816 , 0.88143417, 0.24553193, 0.59634846, 0.41795477,
        0.31300951, 0.41619675, 0.74525927, 0.18940286, 0.31657489],
       [0.97540128, 0.30300034, 0.03611387, 0.04757003, 0.49088451,
        0.03280207, 0.25671455, 0.81027712, 0.42895489, 0.43319987],
       [0.59266865, 0.05838477, 0.3776831 , 0.11243897, 0.1815665 ,
        0.79017353, 0.38291846, 0.63056621, 0.3392219 , 0.58298961],
       [0.46919157, 0.01541027, 0.85093134, 0.32193436, 0.03649847,
        0.78512176, 0.23629257, 0.32596811, 0.06832971, 0.87921063],
       [0.00743982, 0.91935686, 0.26145823, 0.12111866, 0.28090538,
        0.60713329, 0.13656523, 0.5849802 , 0.84474244, 0.88350072],
       [0.59018854, 0.09433462, 0.02039849, 0.19480577, 0.63055252,
        0.40334435, 0.40560017, 0.40113303, 0.96241999, 0.16040671],
       [0.76237398, 0.99885822, 0.9442072

#### Create an array of 20 linearly spaced points between 0 and 1:

In [28]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [29]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [34]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [35]:
mat[3,4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [36]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [37]:
mat[4]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [38]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [39]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [40]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [41]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

# Great Job!